# Generated by Django 3.2.8 on 2021-11-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda_contactos', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_confirm',
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Agenda_contactos.usuario'),
        ),
    ]
