# Generated by Django 3.2.8 on 2021-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda_contactos', '0004_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
