# Generated by Django 3.2.8 on 2021-11-12 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agenda_contactos', '0005_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
