# Generated by Django 3.2.8 on 2021-11-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notitas',
            old_name='continido',
            new_name='contenido',
        ),
        migrations.AlterField(
            model_name='notitas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
