# Generated by Django 3.2.8 on 2021-11-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notitas', '0002_auto_20211121_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notitas',
            name='descripcion',
        ),
    ]
