# Generated by Django 3.2.8 on 2022-01-05 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notitas', '0004_remove_notitas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='notitas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
